### ISSUE TITLE
URL Input Error not displayed if previous result was a valid URL

### ISSUE THREAD

**Issue by ghost** [mlongerich/url_shortener#1]
If I try and enter an invalid URL (for example, by adding a space at the end), after generating a valid URL, the backend will return HTTP500 with an error, but the frontend will show only the most recently generated successfully generated URL:

```
Link Exists (0.5ms)  SELECT  1 AS one FROM "links" WHERE LOWER("links"."short_url") = LOWER($1) LIMIT $2  [["short_url", "000001"], ["LIMIT", 1]]
  ↳ app/controllers/links_controller.rb:17
   (0.2ms)  ROLLBACK
  ↳ app/controllers/links_controller.rb:17
Completed 500 Internal Server Error in 20ms (ActiveRecord: 4.2ms)


  
URI::InvalidURIError (bad URI(is not URI?): http://localhost:300121 ):
  
app/models/link.rb:20:in `valid_url'
app/controllers/links_controller.rb:17:in `create'
```

![image](https://user-images.githubusercontent.com/12702516/46929881-ba965c00-d074-11e8-9946-4af0019db4a9.png)

**Comment by mlongerich** [comment]
@DouglasSanders 

Thank you for letting me know about this. 

To address the issue I have escaped all special characters and have stripped leading and trailing whitespaces. 

If a special character has been inserted it has probably been done so on purpose. 

However, if a space has been inserted, then this was probably done on accident (most likely copy paste error, or keyboard entry error). Therefore to improve the user experience I have opted to just remove the whitespace errors and process the "correct" url.
